const translations = {
  fr: {
    "nav.features": "Fonctions",
    "nav.workflow": "Parcours",
    "nav.download": "Installer",
    "hero.eyebrow": "Client Jellyfin pour Android et Wear OS",
    "hero.text":
      "Retrouvez votre musique Jellyfin sur le telephone, envoyez la connexion a votre montre et controlez la lecture en quelques gestes.",
    "hero.primary": "Installer les builds",
    "hero.secondary": "Comprendre l'app",
    "mock.hello": "Bonjour Valentin",
    "mock.search": "Recherche",
    "mock.track1": "Ocean Drive",
    "mock.artist1": "Playlist Jellyfin",
    "mock.track2": "Late Night Audio",
    "mock.artist2": "Album recent",
    "mock.now": "Lecture en cours",
    "mock.device": "Telephone et montre",
    "mock.watch": "Controle montre",
    "summary.one.title": "Jellyfin d'abord",
    "summary.one.text": "Connexion par serveur, utilisateur et mot de passe.",
    "summary.two.title": "Mobile + montre",
    "summary.two.text": "Le telephone transmet la session a Wear OS.",
    "summary.three.title": "Lecture rapide",
    "summary.three.text": "Reprendre, recents, non lus, recherche et file d'attente.",
    "features.eyebrow": "Ce que fait MusicFin",
    "features.title": "Une interface courte pour aller vite dans votre bibliotheque audio.",
    "features.library.title": "Bibliotheques Jellyfin",
    "features.library.text":
      "MusicFin affiche les bibliotheques musique et livres audio, puis charge les pistes avec pochettes, artistes et albums.",
    "features.playback.title": "Lecture integree",
    "features.playback.text": "Controlez play, pause, piste suivante et precedente depuis le telephone ou la montre.",
    "features.watch.title": "Connexion montre",
    "features.watch.text":
      "Le mobile envoie les identifiants a Wear OS pour eviter de retaper l'adresse Jellyfin sur un petit ecran.",
    "features.offline.title": "Mode montre soigne",
    "features.offline.text":
      "Sur Wear OS, MusicFin propose details de piste, file d'attente, recherche vocale, volume et telechargement hors-ligne.",
    "workflow.eyebrow": "Parcours simple",
    "workflow.title": "Trois etapes pour passer de Jellyfin a la montre.",
    "workflow.step1.title": "Connectez Jellyfin",
    "workflow.step1.text": "Entrez l'adresse du serveur, votre utilisateur et votre mot de passe dans l'app Android.",
    "workflow.step2.title": "Envoyez a la montre",
    "workflow.step2.text": "Le bouton Montre partage la connexion avec l'app Wear OS appairee.",
    "workflow.step3.title": "Lancez la lecture",
    "workflow.step3.text": "Choisissez une bibliotheque, reprenez une piste ou controlez le player depuis le poignet.",
    "download.eyebrow": "Builds locaux",
    "download.title": "Tester MusicFin sur telephone et montre.",
    "download.text":
      "Les APK debug existent deja dans le projet. Installez le client telephone, puis l'app Wear OS avec la meme signature de build.",
    "download.phone": "APK Android",
    "download.watch": "APK Wear OS",
    "footer.text": "MusicFin est un projet compagnon Jellyfin pour garder votre audio a portee de main.",
  },
  en: {
    "nav.features": "Features",
    "nav.workflow": "Flow",
    "nav.download": "Install",
    "hero.eyebrow": "Jellyfin client for Android and Wear OS",
    "hero.text":
      "Bring your Jellyfin music to your phone, send the login to your watch, and control playback in a few taps.",
    "hero.primary": "Install builds",
    "hero.secondary": "Understand the app",
    "mock.hello": "Hello Valentin",
    "mock.search": "Search",
    "mock.track1": "Ocean Drive",
    "mock.artist1": "Jellyfin playlist",
    "mock.track2": "Late Night Audio",
    "mock.artist2": "Recent album",
    "mock.now": "Now playing",
    "mock.device": "Phone and watch",
    "mock.watch": "Watch control",
    "summary.one.title": "Jellyfin first",
    "summary.one.text": "Sign in with server, username, and password.",
    "summary.two.title": "Phone + watch",
    "summary.two.text": "The phone passes the session to Wear OS.",
    "summary.three.title": "Fast playback",
    "summary.three.text": "Resume, recent, unplayed, search, and queue.",
    "features.eyebrow": "What MusicFin does",
    "features.title": "A compact interface for moving quickly through your audio library.",
    "features.library.title": "Jellyfin libraries",
    "features.library.text":
      "MusicFin shows music and audiobook libraries, then loads tracks with covers, artists, and albums.",
    "features.playback.title": "Built-in playback",
    "features.playback.text": "Control play, pause, next, and previous from your phone or watch.",
    "features.watch.title": "Watch login",
    "features.watch.text":
      "The phone sends credentials to Wear OS so you do not have to type the Jellyfin address on a tiny screen.",
    "features.offline.title": "Careful watch mode",
    "features.offline.text":
      "On Wear OS, MusicFin includes track details, queue, voice search, volume, and offline downloads.",
    "workflow.eyebrow": "Simple flow",
    "workflow.title": "Three steps from Jellyfin to your watch.",
    "workflow.step1.title": "Connect Jellyfin",
    "workflow.step1.text": "Enter the server address, username, and password in the Android app.",
    "workflow.step2.title": "Send to the watch",
    "workflow.step2.text": "The Watch button shares the session with the paired Wear OS app.",
    "workflow.step3.title": "Start playback",
    "workflow.step3.text": "Pick a library, resume a track, or control the player from your wrist.",
    "download.eyebrow": "Local builds",
